import logging
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from typing import Dict, List

from ..checks.base import CheckResult, Finding, Severity
from .base import BaseAlerter

logger = logging.getLogger(__name__)

_SEVERITY_ORDER = ["critical", "high", "medium", "low", "info"]


def _severity_rank_value(severity_value: str) -> int:
    return {"info": 0, "low": 1, "medium": 2, "high": 3, "critical": 4}.get(severity_value, 0)


def _build_plain_text(
    qualifying: List[tuple],
    run_timestamp: str,
    critical_count: int,
    high_count: int,
) -> str:
    lines = [
        f"Network Bot Alert — {run_timestamp}",
        f"{critical_count} Critical, {high_count} High findings detected.",
        "",
        "=" * 60,
    ]

    # Group by severity then by target
    by_severity: Dict[str, Dict[str, List[Finding]]] = {}
    for target, finding in qualifying:
        sev = finding.severity.value
        by_severity.setdefault(sev, {}).setdefault(target, []).append(finding)

    for sev in _SEVERITY_ORDER:
        if sev not in by_severity:
            continue
        lines.append(f"\n[{sev.upper()}]")
        lines.append("-" * 40)
        for target, findings in by_severity[sev].items():
            lines.append(f"  Target: {target}")
            for f in findings:
                lines.append(f"    - {f.title}")
                if f.description:
                    lines.append(f"      {f.description}")

    lines.append("")
    lines.append("=" * 60)
    lines.append("Generated by Network Bot")
    return "\n".join(lines)


def _build_html(
    qualifying: List[tuple],
    run_timestamp: str,
    critical_count: int,
    high_count: int,
) -> str:
    sev_colors = {
        "critical": "#dc3545",
        "high": "#fd7e14",
        "medium": "#ffc107",
        "low": "#28a745",
        "info": "#17a2b8",
    }

    by_severity: Dict[str, Dict[str, List[Finding]]] = {}
    for target, finding in qualifying:
        sev = finding.severity.value
        by_severity.setdefault(sev, {}).setdefault(target, []).append(finding)

    rows_html = ""
    for sev in _SEVERITY_ORDER:
        if sev not in by_severity:
            continue
        color = sev_colors.get(sev, "#6c757d")
        for target, findings in by_severity[sev].items():
            for f in findings:
                rows_html += (
                    f"<tr>"
                    f"<td style='padding:6px 10px;border:1px solid #dee2e6;'>{target}</td>"
                    f"<td style='padding:6px 10px;border:1px solid #dee2e6;"
                    f"color:{color};font-weight:bold;'>{sev.upper()}</td>"
                    f"<td style='padding:6px 10px;border:1px solid #dee2e6;'>{f.title}</td>"
                    f"<td style='padding:6px 10px;border:1px solid #dee2e6;font-size:0.9em;'>{f.description}</td>"
                    f"</tr>"
                )

    html = f"""<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><title>Network Bot Alert</title></head>
<body style="font-family:Arial,sans-serif;color:#333;max-width:900px;margin:auto;padding:20px;">
  <h2 style="color:#dc3545;">Network Bot Alert</h2>
  <p><strong>Timestamp:</strong> {run_timestamp}</p>
  <p><strong>Summary:</strong> {critical_count} Critical, {high_count} High findings detected.</p>
  <table style="border-collapse:collapse;width:100%;margin-top:20px;">
    <thead>
      <tr style="background:#f8f9fa;">
        <th style="padding:8px 10px;border:1px solid #dee2e6;text-align:left;">Target</th>
        <th style="padding:8px 10px;border:1px solid #dee2e6;text-align:left;">Severity</th>
        <th style="padding:8px 10px;border:1px solid #dee2e6;text-align:left;">Finding</th>
        <th style="padding:8px 10px;border:1px solid #dee2e6;text-align:left;">Description</th>
      </tr>
    </thead>
    <tbody>
      {rows_html}
    </tbody>
  </table>
  <p style="margin-top:30px;font-size:0.85em;color:#6c757d;">Generated by Network Bot</p>
</body>
</html>"""
    return html


class EmailAlerter(BaseAlerter):
    @property
    def name(self) -> str:
        return "email"

    def send(self, results: List[CheckResult], run_timestamp: str) -> None:
        smtp_host = self.config.get("smtp_host", "")
        smtp_port = int(self.config.get("smtp_port", 587))
        smtp_user = self.config.get("smtp_user", "")
        smtp_password = self.config.get("smtp_password", "")
        from_addr = self.config.get("from_addr", "")
        to_addrs = self.config.get("to_addrs", [])
        use_tls = bool(self.config.get("use_tls", True))
        min_severity = self.config.get("min_severity", "high")

        if not smtp_host or not from_addr or not to_addrs:
            logger.error("EmailAlerter: smtp_host, from_addr, and to_addrs are required")
            return

        min_rank = _severity_rank_value(min_severity)

        qualifying: List[tuple] = []
        for result in results:
            for finding in result.findings:
                if _severity_rank_value(finding.severity.value) >= min_rank:
                    qualifying.append((result.target, finding))

        if not qualifying:
            logger.debug("EmailAlerter: no findings at or above %s; skipping", min_severity)
            return

        critical_count = sum(1 for _, f in qualifying if f.severity == Severity.CRITICAL)
        high_count = sum(1 for _, f in qualifying if f.severity == Severity.HIGH)

        subject = (
            f"[Network Bot] {critical_count} Critical, {high_count} High findings — {run_timestamp}"
        )

        plain_text = _build_plain_text(qualifying, run_timestamp, critical_count, high_count)
        html_body = _build_html(qualifying, run_timestamp, critical_count, high_count)

        msg = MIMEMultipart("alternative")
        msg["Subject"] = subject
        msg["From"] = from_addr
        msg["To"] = ", ".join(to_addrs)
        msg.attach(MIMEText(plain_text, "plain", "utf-8"))
        msg.attach(MIMEText(html_body, "html", "utf-8"))

        try:
            if use_tls:
                server = smtplib.SMTP(smtp_host, smtp_port, timeout=15)
                server.ehlo()
                server.starttls()
                server.ehlo()
            else:
                server = smtplib.SMTP(smtp_host, smtp_port, timeout=15)
                server.ehlo()

            if smtp_user and smtp_password:
                server.login(smtp_user, smtp_password)

            server.sendmail(from_addr, to_addrs, msg.as_string())
            server.quit()
            logger.info("EmailAlerter: alert sent to %s (%d findings)", to_addrs, len(qualifying))
        except smtplib.SMTPException as exc:
            logger.error("EmailAlerter: failed to send alert: %s", exc)
        except OSError as exc:
            logger.error("EmailAlerter: connection error: %s", exc)
